### ISSUE TITLE
请问您提到有一些场次需要指定身份 id 实名，那这种场次在发请求时需要多加一个id的参数吗

### ISSUE THREAD

**Issue by xixidadaer** [ronething/xiudong-go#1]
有看到您在readme里提到有一些场次需要指定身份 id 实名，1）这一般是什么场次会要求这种信息呀，2）如果需要这个id信息的场次抢票的时候只输入select_num=1是否足够，还是说发请求时需要多加一个id的参数吗？ 谢谢！！

**Comment by ronething** [comment]
@xixidadaer 获取身份 id 对于 xiudong-selenium 暂时没什么实质性的作用。

> 这一般是什么场次会要求这种信息呀

有一些场次购买的时候需要指定实名观演人，获取 ticketId 的时候不需要指定身份 id

> 如果需要这个id信息的场次抢票的时候只输入select_num=1是否足够

对于 xiudong-selenium 来说，足够。

**Comment by xixidadaer** [comment]
好的了解，非常感谢您的解答！
