### ISSUE TITLE
软件打开

### ISSUE THREAD

**Issue by Oicite** [ronething/xiudong-go#13]
软件刚打开就闪退
请问一下使用教程

**Comment by ronething** [comment]
这是命令行工具。双击打开之后退出是正常的。
需要打开一个终端，然后输入如下的字符。
```
./showstart.exe -h 
```

**Comment by Oicite** [comment]
![image](https://github.com/ronething/xiudong-go/assets/149748604/b20cf7ee-72c9-40bc-87f2-1c14af96d37c)
这是为啥

**Comment by Oicite** [comment]
![image](https://github.com/ronething/xiudong-go/assets/149748604/304fce2a-087f-4ad2-8df0-1c2b67396749)
qingwen请问一下作者这样是啥情况

**Comment by Oicite** [comment]
![image](https://github.com/ronething/xiudong-go/assets/149748604/fbb01b63-c670-497f-8f01-09477b28d2ad)
请问一下作者这样是啥情况打开之后还是会闪退

**Comment by Oicite** [comment]
作者请问怎么抢票

**Comment by ronething** [comment]
这个工具不支持。https://github.com/ronething/xiudong-selenium 有需要可以看看这个。
