### ISSUE TITLE
question: how to set config filepath

### ISSUE THREAD

**Issue by 1178631106** [ronething/xiudong-go#3]

**Comment by 1178631106** [comment]
大佬，为什么配置完yaml文件，还是一直nil config啊

**Comment by ronething** [comment]
@1178631106 可以使用 --config 指定配置文件试试

**Comment by 1178631106** [comment]
谢谢您的回复。默认的是showstart.yaml 我是直接在那里面改的啊
&nbsp;


有何不可℡
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ashing ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ronething/xiudong-go] order命令能给个例子吗 (Issue #3)





 
@1178631106 可以使用 --config 指定配置文件试试

**Comment by 1178631106** [comment]
![image](https://user-images.githubusercontent.com/48510632/232218484-77c893b3-4586-482a-867d-aabb9efca458.png)
大哥 您看

**Comment by 1178631106** [comment]
![image](https://user-images.githubusercontent.com/48510632/232220258-ad53d518-1db5-46bf-88f8-ec5a95e2ab56.png)
刚刚那个不对...

**Comment by 1178631106** [comment]
大哥 我悟了

**Comment by ronething** [comment]
有其他问题可再提新 issue

**Comment by 1178631106** [comment]
好的 已经能查到了 谢谢大佬
