### ISSUE TITLE
关于获取观影人列表失败的解决方法

### ISSUE THREAD

**Issue by Thehayhua** [ronething/xiudong-go#8]
![image](https://github.com/ronething/xiudong-go/assets/103148790/cadd5983-1153-4502-9479-40a996106bb6)

**Comment by ronething** [comment]
please use v0.0.2: https://github.com/ronething/xiudong-go/releases/tag/v0.0.2

**Comment by ronething** [comment]
if it still have a problem, please create a new issue.
